### ISSUE TITLE
Aspect rules for specific objects

### ISSUE THREAD

**Issue by NodBr** [theriftlab/immanuel-python#12]
Hi @theriftlab,

I am collaborating with an astrologer on a project where we are using the Immanuel library to implement some specific astrological rules. While we've successfully integrated several rules, we're encountering challenges with others.

Here are some examples of her specific requirements:
- The Ascendant (ASC) should engage in standard aspects (conjunctions, oppositions, etc.), but other angles like the Descendant (DSC), Midheaven (MC), and Imum Coeli (IC) should neither form nor receive aspects.
- Lilith should be able to form and receive conjunctions, oppositions, and trines, and also receive squares.
- The Part of Fortune should only receive conjunctions and not form aspects.

I've attempted to use the settings module as suggested in the documentation, but it didn’t work for these particular cases.

Currently, I generate the chart and then manually filter out non-compliant aspects from the chart.aspects dictionary using multiple loops. This method is quite inefficient, particularly as our project has more specific needs. I would prefer not to loop for every little detail.

Is there a more streamlined way within the library to apply these rules before generating the chart? I've tried several approaches without success and couldn’t find relevant guidance in the documentation.

Thank you for your assistance.

**Comment by theriftlab** [comment]
This should be possible within the settings - if this doesn't work there's likely a bug somewhere!

```python
from immanuel.const import calc, chart
from immanuel.setup import settings


settings.aspect_rules = {
    chart.ASC: {
        'initiate': settings.aspects,
        'receive': settings.aspects,
    },
    chart.DESC: {
        'initiate': [],
        'receive': [],
    },
    chart.MC: {
        'initiate': [],
        'receive': [],
    },
    chart.IC: {
        'initiate': [],
        'receive': [],
    },
    chart.TRUE_LILITH: {
        'initiate': [
            calc.CONJUNCTION,
            calc.OPPOSITION,
            calc.TRINE,
        ],
        'receive': [
            calc.CONJUNCTION,
            calc.OPPOSITION,
            calc.TRINE,
            calc.SQUARE,
        ],
    },
    chart.PARS_FORTUNA: {
        'initiate': [],
        'receive': [
            calc.CONJUNCTION,
        ],
    }
}
```

**Comment by NodBr** [comment]
Wow! It worked perfectly.
In fact, I've never used the "chart.xxxx" syntax at all in my code, just the numbers, like 3000002 for DSC. It woked everywhere in my code, except here.
In the future, I'll revise my code and try switch my mindset to the chart.xxxx syntax and see if it becomes more efficient and more cleanly-coded.
Thanks a lot.

**Comment by theriftlab** [comment]
It's best to stick to the constants since even the existing ones are subject to change if/when new object are added - which won't be often but probably often enough to mess up code relying on pure values.
