### ISSUE TITLE
Points not working properly

### ISSUE THREAD

**Issue by NodBr** [theriftlab/immanuel-python#13]
HI @theriftlab 

I saw your last commit, but noticed an odd behavior on my code.
Then, I ran a simple test, like the ones you have on the 'test' folder

```
from immanuel.const import chart

print (
    chart.NORTH_NODE,
    chart.SOUTH_NODE,
    chart.TRUE_NORTH_NODE,
    chart.TRUE_SOUTH_NODE,
    chart.VERTEX,
    chart.LILITH,
    chart.TRUE_LILITH,
    chart.INTERPOLATED_LILITH,
    chart.SYZYGY,
    chart.PART_OF_FORTUNE,
    chart.PART_OF_SPIRIT,
)
```

It seems like the code is not compliant with numbers on [this file](https://github.com/theriftlab/immanuel-python/blob/master/immanuel/const/chart.py):
- Syzygy is still the old number
- No chart.INTERPOLATED_LILITH
- No PART_OF_FORTUNE (it's still responding to the old name)
- No chart.PART_OF_SPIRIT

So it seems that, although you updated that link, some part of the code just "didn´t get the memo"

**Comment by theriftlab** [comment]
I haven't pushed these to a release yet so you won't be able to `pip install` the new features. The `master` branch is rarely production-ready, but if you do want to play with any cutting-edge changes you can clone a copy of the repo on your computer and `pip install -e /path/to/repo` and that should give you the latest, if I've recalled that correctly (also you will probably have to uninstall the currently-installed Immanuel first). Then you can just `git pull` on your local repo every time there's a change you want. Be warned `master` might be broken or incomplete if I'm halfway through a change (eg. these new objects have no translations yet). This is bad practice on my part lol, I'm trying to get more organized with my Git branches.
