### ISSUE TITLE
Regarding the issue of calculating differences in house cusps

### ISSUE THREAD

**Issue by sunny3721BABY** [theriftlab/immanuel-python#14]
# when comparing the house cusps at the same moment and location under the same house system using ASTROLOG 7.6 as a reference, where does this discrepancy arise? Thank you!

timestr = datetime.strftime(datetime.utcnow(), '%Y-%m-%d %H:%M:%S')
native = charts.Subject(
    date_time=timestr,
    latitude='51N00',
    longitude='00W00',
)

default_body = charts.Natal(native)

print(default_body._houses)
print(default_body.native)
print(default_body.house_system)
print("moon:", default_body.moon_phase)
for house in default_body.houses.values():
    print(house)

----------------------------------------------------->>>
Thu May 16 2024 10:05:47 BST at 51N0.0, 0E0.0
Placidus
moon: First Quarter
1st House 04°10'47" in Leo
2nd House 21°02'02" in Leo
3rd House 12°30'17" in Virgo
4th House 11°58'56" in Libra
5th House 21°23'01" in Scorpio
6th House 02°21'42" in Capricorn
7th House 04°10'47" in Aquarius
8th House 21°02'02" in Aquarius
9th House 12°30'17" in Pisces
10th House 11°58'56" in Aries
11th House 21°23'01" in Taurus
12th House 02°21'42" in Cancer
![ASTRO76](https://github.com/theriftlab/immanuel-python/assets/160033537/671c3bf3-67e9-4e9e-a9aa-5890a92dbb8a)

**Comment by theriftlab** [comment]
I receive many of these - please double-check your timezones! The UK is currently in BST, which is UTC+1. Immanuel takes the date/time as local - in this case, 10am BST, which is 9am UTC. It appears that Astrolog has taken the date/time as UTC which shifts the results ahead of Immanuel by an hour.

**Comment by sunny3721BABY** [comment]
I have set all latitudes to 0 degrees and it's working fine so far. Also, could you please tell me how to set the immanuel library to work in heliocentric mode? Thank you!

**Comment by theriftlab** [comment]
Great to hear it's working! Immanuel is currently geocentric only. Helio might be something I look into implementing in the future, but unfortunately it won't be for a while.
