### ISSUE TITLE
how to include dignities and scores in natal.objects

### ISSUE THREAD

**Issue by kkkhora** [theriftlab/immanuel-python#15]
Hi, first of all, thank you for providing this well-written api in astrology! I'm really enjoying it!

When I tried to output natal.objects in JSON format, the output didn't include dignities and score by default. I have read the docs and tried with settings and reports module, but still failed to include the dignities data. Could you please guide me on how to include dignities data in the natal.objects output? Thank you!

Here's what I have imported:
<img width="399" alt="Screenshot 2024-05-29 at 12 31 40" src="https://github.com/theriftlab/immanuel-python/assets/76552190/56f71b67-e6a4-4192-8551-5b157effcdf9">
I assume I should do something with the setting. But I'm not sure how to do it. 

This is what I called to get the natal.objects data: 
print(json.dumps(natal.objects, cls=ToJSON, indent=4))

The output data ends with the key "out_of_bound", without "dignities" and "score" as displayed in doc/examples or doc/data
<img width="319" alt="Screenshot 2024-05-29 at 12 25 23" src="https://github.com/theriftlab/immanuel-python/assets/76552190/df79ad7f-c332-418d-b6f2-358c0cc42643">

**Comment by theriftlab** [comment]
I'm glad you're finding Immanuel useful! This is a bug, dignities should always show for all planets, as long as all planets are included in the chart (which they are by default).

I have pushed up v1.4.1 which should address this & dignities should be back.

**Comment by kkkhora** [comment]
The new version is working well. Thank you very much for your prompt response. I will keep you informed if I encounter any further issues.
