### ISSUE TITLE
the index of fixed stars

### ISSUE THREAD

**Issue by sunny3721BABY** [theriftlab/immanuel-python#17]
settings.objects.extend(['Antares','Rigel','Hamal', 'Vindemiatrix', 'Regulus', 'Aldebaran', 'Fomalhaut'])
    for index, aspects in birth2_chart.aspects.items():
        for aspect in aspects.values():
            if aspect.active in [chart.MOON, chart.SUN] and birth2_chart.objects[aspect.passive].name in ['Rigel', 'Hamal', 'Regulus']:
                if aspect.aspect == 0.0 and aspect.difference.raw < 1.0:
                    birth2aspect.append((birth2_chart.objects[aspect.active].name,
                                         birth2_chart.objects[aspect.passive].name, aspect.aspect))

                    print(
                        f' birth2_Lightbody:{aspect.active}-fixstar:{aspect.passive}-forms:{aspect.aspect}-{aspect.difference}-{curr_time}')##print:birth2_Lightbody:4000001-fixstar:Hamal-forms:0.0-00°41'22"-2024-04-28 12:00:00
Hello, theriftlab, is the issue that the index of fixed stars cannot be set as an integer due to my settings or is there another reason?

**Comment by theriftlab** [comment]
What issue are you having? Can you either post what errors you're seeing, or post the whole code?

**Comment by sunny3721BABY** [comment]
The problem is solved.
