### ISSUE TITLE
Ceres etc. problem

### ISSUE THREAD

**Issue by ultratronic** [theriftlab/immanuel-python#18]
Dear @theriftlab,

Thank you for very well structured code. I have an issue to print Ceres, Pallas Juno Vesta Part_of_spirit. They have the codes in docs but when i try to print them, there aren't in natal objects. 

Should i import any other Ephemeris file I couldn't understand.

Could you please help me?

**Comment by theriftlab** [comment]
Not every chart object is included by default - you can choose which ones are returned using the settings as per the docs: https://github.com/theriftlab/immanuel-python/blob/v1.4.1/docs/5-settings.md#objects

So for example, to print out the defaults plus the extra ones you want:

```python
from immanuel.const import chart
from immanuel.setup import settings
from immanuel import charts

latitude = '32n43'
longitude = '117w09'
date_time = '2000-01-01 10:00'

settings.objects.extend([chart.CERES, chart.PALLAS, chart.JUNO, chart.VESTA, chart.PART_OF_SPIRIT])

native = charts.Subject(date_time, latitude, longitude)
natal = charts.Natal(native)

for obj in natal.objects.values():
    print(obj)
```

**Comment by ultratronic** [comment]
Thank You So Much
