### ISSUE TITLE
Find Function - Angles and Houses

### ISSUE THREAD

**Issue by NodBr** [theriftlab/immanuel-python#4]
I don't know if it's on any plan you have for the library.

I've being exploring the find function, which is very cool, but I encontered a limitattion: it only deals with planets (the "4000000" objects). I don't know how difficult it will be, but I think it will be great if we could work with other objects.

Let me give three examples:
1 - I wanna calculate the sunrise for a given day. So I could ask it to find when the Sun and the ASC will make a conjunction. But it gives me an error, because it calls functions that need information I can't provide.
2 - I could use it to find when a given object will be in a given sign
3 - Or it could help find, when a planet it will enter my 10th house. 

Whenever you are thinking about upgrades on the find funcion (os similar function), it will be great if it receive these options.

**Comment by theriftlab** [comment]
This is something I've already been mulling over actually, getting future transits into the chart classes. The submodules, including `find`, are mainly for the benefit of the chart classes to gather data (although they are generally designed to be simple enough to use separately) so `find` will need some new helper functions adding, but ultimately I'd like to add new functionality into the chart classes. That way we can get user-friendly & JSON output. I will have a think over this!

**Comment by NodBr** [comment]
I do understand how difficult it can be to do something like this, especially with all retrograde planets, variable speeds and everything else.

Another idea related to this, but I supose even more complex, would be a function where you pass:
- A chart (Natal, composite or progressed)
- An object of this chart (obj1)
- Another object (obj2)
- An aspect (conjunction, square, etc)
It will check the absolute position of obj1 and show when obj2 make that aspect to obj1.

So, you could predict when Mars will enter your Natal 4th House, or when the Sun will make an opposition to your progressed Lilith, or when will the moon make a Conjunction to the composite chart you have with your wife.

Anyway, I know it's much easier said then done, but I hope it shows how fantastic your library is.

**Comment by theriftlab** [comment]
Closing this as it's getting absorbed into #9
