### ISSUE TITLE
swisseph.Error: swisseph.calc_ut: SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/'

### ISSUE THREAD

**Issue by liu124** [theriftlab/immanuel-python#6]
![企业微信截图_1713174772645](https://github.com/theriftlab/immanuel-python/assets/29817248/7a506573-d5ca-4f88-ab8e-64235ae9509e)

**Comment by theriftlab** [comment]
I have pushed a new release containing several changes and a few fixes - try `pip install --upgrade immanuel` to get v1.3.2 to see if this works? I'm not too sure otherwise as I've not seen this error before.
