### ISSUE TITLE
have  below picture data

### ISSUE THREAD

**Issue by liu124** [theriftlab/immanuel-python#7]
![企业微信截图_17131865797429](https://github.com/theriftlab/immanuel-python/assets/29817248/30d221b9-82a7-4895-bb55-90307617a3fa)

**Comment by theriftlab** [comment]
I'm not sure what all the 3rd column is, but I'm guessing it's the tolerance within which an orb is considered "exact" or not. You can change the orbs for each planet / object using `settings` - this can get quite detailed, so it is best to check out the documentation around [here](https://github.com/theriftlab/immanuel-python/blob/v1.3.2/docs/5-settings.md#planet_orbs) - just above the `planet_orbs` section you will see there is an `exact_orb` setting which defines the tolerance for calculating exact orbs, but this is applied across all aspects, and cannot be defined individually per aspect.
